### ISSUE TITLE
Multiplying by commensurable units doesn't convert units correctly

### ISSUE THREAD

**Issue by andrewminer** [trzemecki/Unum#2]
For example:

```
IN = new_unit("in", 0, "inch")
FT = new_unit("ft", 12 * IN, "foot")

a = 10 * FT
b = 2 * IN

c = a * b
d = a / b
```

In this case, I'd expect `c` to equal either `240in²` or `1.667ft²`.  Instead I get `20ft•in`.  Likewise, I'd expect `d` to be `60` (with no unit).  Instead, I get `5ft/in`.

**Comment by trzemecki** [comment]
I turned off default auto normalization because I want to display units like N*m/m

For turn it on please call

`unum.Unum.formatter.configure(auto_norm=True)`

**Comment by trzemecki** [comment]
```
>>> c.cast_unit(FT**2)
1.66666666667 [ft2]
