### ISSUE TITLE
Error while checking for nonzeroness of a Unit

### ISSUE THREAD

**Issue by Torilla** [trzemecki/Unum#6]
When checking the boolean character of a unit I get a TypeError in the internal code:

```python
>>> from unum.units import *
>>> bool(5*angstrom)
```
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../unum/__init__.py", line 440, in __len__
    return len(self._value)
TypeError: object of type 'int' has no len()
```
This happens irrelevant of the value of the unit.
Also I am not sure if a 0 numerical value unit should return False or True when checked for the boolean character.

**Comment by trzemecki** [comment]
Ok, it seems that I missed __bool__ function. Fixed.
